name: Deploy release to production
on:
  push:
    branches:
      - 'release/production'
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
  setup-node:
    name: Setup node
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        shell: bash
        run: npm install
  create-config:
    name: Create config
    runs-on: ubuntu-latest
    steps:
      - name: create config
        uses: ./.github/actions/create_config
        with:
          name: ${{ secrets.BOT_NAME }}
          avatar: ${{ secrets.BOT_AVATAR }}
          type: bot
          main: dist/index.js
          ram: ${{ secrets.BOT_RAM }}
          autorestart: true
          version: latest
          apt: tools
  create-env:
    name: Create .env file
    runs-on: ubuntu-latest
    steps:
      - name: create .env file
        uses: ./.github/actions/create_env
        with:
          token: ${{ secrets.BOT_TOKEN }}
          client_id: ${{ secrets.BOT_CLIENT_ID }}
          guild_id: ${{ secrets.BOT_GUILD_ID }}
          bot_color: ${{ secrets.BOT_COLOR }}
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_secret: ${{ secrets.SPOTIFY_SECRET }}
          idle_time_seconds: ${{ secrets.IDLE_TIME_SECONDS }}
          env: production
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [create-config, create-env]
    steps:
      - name: publish
        uses: ./.github/actions/publish
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}
          app_id: ${{ secrets.DISCLOUD_APP_ID }}