name: On release
on:
  push:
    branches:
      - 'release/production'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: clean
        uses: taylorgibb/ftp-clean@v2.0.3
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_HOST }}|${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: '[".env"]'
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: copy
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          delete: false