name: Deploy release to production
on:
  push:
    branches:
      - 'release/production'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: install dependencies
        shell: bash
        run: npm install
      - name: build
        shell: bash
        run: npm run build
      - name: create config
        uses: ./.github/actions/create_config
        with:
          name: ${{ secrets.BOT_NAME }}
          avatar: ${{ secrets.BOT_AVATAR }}
          type: bot
          main: dist/index.js
          ram: ${{ secrets.BOT_RAM }}
          autorestart: true
          version: latest
          apt: tools
      - name: create .env file
        uses: ./.github/actions/create_env
        with:
          token: ${{ secrets.BOT_TOKEN }}
          client_id: ${{ secrets.BOT_CLIENT_ID }}
          guild_id: ${{ secrets.BOT_GUILD_ID }}
          bot_color: ${{ secrets.BOT_COLOR }}
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_secret: ${{ secrets.SPOTIFY_SECRET }}
          idle_time_seconds: ${{ secrets.IDLE_TIME_SECONDS }}
          env: production
      - name: publish
        uses: ./.github/actions/publish
        with:
          token: ${{ secrets.DISCLOUD_TOKEN }}
          app_id: ${{ secrets.DISCLOUD_APP_ID }}